### ISSUE TITLE
Docs need to be updated -o options doesn't exist.

### ISSUE THREAD

**Issue by AdamKyle** [promiscuous-io/promiscuous#47]
When running the command from the docs to generate a mock, I get the error that -o doesn't exist, well it actually doesn't. The source shows nothing in relation to these arguments. So what is the correct command?

```
bundle exec promiscuous mocks -o generated_mocks.rb
OptionParser::InvalidOption: invalid option: -o
--------------------------------------------------------------------------------
/Users/Adam/.rvm/gems/ruby-2.1.1/gems/promiscuous-0.25/lib/promiscuous/cli.rb:125:in `parse_args'
/Users/Adam/.rvm/gems/ruby-2.1.1/gems/promiscuous-0.25/lib/promiscuous/cli.rb:150:in `run'
/Users/Adam/.rvm/gems/ruby-2.1.1/gems/promiscuous-0.25/bin/promiscuous:5:in `<top (required)>'
/Users/Adam/.rvm/gems/ruby-2.1.1/bin/promiscuous:23:in `load'
/Users/Adam/.rvm/gems/ruby-2.1.1/bin/promiscuous:23:in `<main>'
/Users/Adam/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
/Users/Adam/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by AdamKyle** [comment]
Issue resulted in an older version being used. You have to specify the latest version with `gem 'promiscuous'`
