### ISSUE TITLE
Issue with running command to start subscriber

### ISSUE THREAD

**Issue by AdamKyle** [promiscuous-io/promiscuous#48]
You're command to start the subscriber isn't working as expected. So whats going on?

```
bundle exec promiscuous subscribe
NoMethodError: undefined method `subscribe' for User(no database connection):Class
--------------------------------------------------------------------------------
/Users/Adam/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.3/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
/Users/Adam/Dropbox/AisisGit/Aisis-Writer/app/models/user.rb:3:in `<class:User>'
/Users/Adam/Dropbox/AisisGit/Aisis-Writer/app/models/user.rb:1:in `<top (required)>'
/Users/Adam/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:424:in `load'
/Users/Adam/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:424:in `block in load_file'
/Users/Adam/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:616:in `new_constants_in'
/Users/Adam/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:423:in `load_file'
/Users/Adam/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:324:in `require_or_load'
/Users/Adam/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:289:in `depend_on'
/Users/Adam/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:207:in `require_dependency'
/Users/Adam/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.0.3/lib/rails/engine.rb:465:in `block (2 levels) in eager_load!'
/Users/Adam/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.0.3/lib/rails/engine.rb:464:in `each'
/Users/Adam/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.0.3/lib/rails/engine.rb:464:in `block in eager_load!'
/Users/Adam/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.0.3/lib/rails/engine.rb:462:in `each'
/Users/Adam/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.0.3/lib/rails/engine.rb:462:in `eager_load!'
/Users/Adam/.rvm/gems/ruby-2.0.0-p353/gems/promiscuous-0.25/lib/promiscuous/cli.rb:145:in `load_app'
/Users/Adam/.rvm/gems/ruby-2.0.0-p353/gems/promiscuous-0.25/lib/promiscuous/cli.rb:151:in `run'
/Users/Adam/.rvm/gems/ruby-2.0.0-p353/gems/promiscuous-0.25/bin/promiscuous:5:in `<top (required)>'
/Users/Adam/.rvm/gems/ruby-2.0.0-p353/bin/promiscuous:23:in `load'
/Users/Adam/.rvm/gems/ruby-2.0.0-p353/bin/promiscuous:23:in `<main>'
```

**Comment by kareemk** [comment]
@AdamKyle it looks like you're using Rails 4, currently promiscuous only supports Rails 3.x.

**Comment by AdamKyle** [comment]
This issue will be closed. It seems when you do `gem 'promiscuous'` you get version 0.25 (the release from January) which is exceptionally old. So you have to specify a version. After that and the addition of the `_v` column to the subscriber table it works in rails 4.1 (the subscriber isn't saving the publishers data, but that's probably because the data from the publisher  comes from `Engine_table_name` and subscribers table name is just `table_name` (I assume they have to be the same table name all around.)
