### ISSUE TITLE
Subscriber side sync error

### ISSUE THREAD

**Issue by samsongz** [promiscuous-io/promiscuous#58]
When trying to run an initial table sync as described in the wiki, I get this error:

```
NoMethodError: undefined method '__promiscuous_eventual_consistency_update' for nil:NilClass while processing {"operations":[{"types":["ImportLogItem"],"id":"1","attributes":{"service":"LICENSE","file_name":"state_license_test.csv","file_downloaded_from":"/StateLicense/spec/data","stats":"{\"csv_file\":\"/StateLicense/spec/data/state_license_test.csv\",\"started_at\":\"2014-06-25T11:58:25-04:00\",\"total_rows\":114,\"updated_rows_count\":98,\"created_rows_count\":15,\"finished_at\":\"2014-06-25T11:58:31-04:00\",\"success_rows_count\":113,\"failed_rows_count\":1}","created_at":"2014-06-25T15:58:35Z","stats_email_sent_to":"jon@example.com","import_errors":"some json string","import_state":"CT","license_type":"LICENSE"},"operation":"update","version":1}],"app":"state_license","timestamp":"2014-06-29T17:34:49-04:00","generation":0,"host":"MacBook.local","dependencies":{"write":["xxx:1"]}}
/gems/promiscuous-1.0.0.beta4/lib/promiscuous/subscriber/operation.rb:51:in 'block in update'
/gems/promiscuous-1.0.0.beta4/lib/promiscuous/subscriber/operation.rb:50:in 'tap'
/gems/promiscuous-1.0.0.beta4/lib/promiscuous/subscriber/operation.rb:50:in 'update'
/gems/promiscuous-1.0.0.beta4/lib/promiscuous/subscriber/operation.rb:71:in 'execute'
/gems/promiscuous-1.0.0.beta4/lib/promiscuous/subscriber/unit_of_work.rb:82:in 'block in execute_operation'
/gems/promiscuous-1.0.0.beta4/lib/promiscuous/subscriber/unit_of_work.rb:69:in with_instance_locked_for'
/gems/promiscuous-1.0.0.beta4/lib/promiscuous/subscriber/unit_of_work.rb:81:in 'execute_operation'
/gems/promiscuous-1.0.0.beta4/lib/promiscuous/subscriber/unit_of_work.rb:88:in 'block (2 levels) in on_message'
/gems/promiscuous-1.0.0.beta4/lib/promiscuous/subscriber/unit_of_work.rb:88:in 'each'
/gems/promiscuous-1.0.0.beta4/lib/promiscuous/subscriber/unit_of_work.rb:88:in 'block in on_message'
/gems/promiscuous-1.0.0.beta4/lib/promiscuous/subscriber/unit_of_work.rb:99:in 'with_transaction'
/gems/promiscuous-1.0.0.beta4/lib/promiscuous/subscriber/unit_of_work.rb:87:in 'on_message'
/gems/promiscuous-1.0.0.beta4/lib/promiscuous/subscriber/unit_of_work.rb:40:in 'process_message'
/gems/promiscuous-1.0.0.beta4/lib/promiscuous/subscriber/unit_of_work.rb:24:in 'process'
/gems/promiscuous-1.0.0.beta4/lib/promiscuous/subscriber/message.rb:46:in 'process'
/gems/promiscuous-1.0.0.beta4/lib/promiscuous/subscriber/worker/runner.rb:39:in 'block (2 levels) in main_loop'
<internal:prelude>:10:in 'synchronize'
/gems/promiscuous-1.0.0.beta4/lib/promiscuous/subscriber/worker/runner.rb:37:in 'block in main_loop'
/gems/promiscuous-1.0.0.beta4/lib/promiscuous/subscriber/worker/runner.rb:35:in 'loop'
/gems/promiscuous-1.0.0.beta4/lib/promiscuous/subscriber/worker/runner.rb:35:in 'main_loop'
/gems/promiscuous-1.0.0.beta4/lib/promiscuous/subscriber/worker/runner.rb:31:in 'block in initialize'
```

Normal creating/updating from promiscuous publisher to subscriber works fine. I can't see anything clearly wrong with the payload and I've tried synching a few different models but get the same issue. Any suggestions for what might be missing from the [update](https://github.com/promiscuous-io/promiscuous/blob/master/lib/promiscuous/subscriber/operation.rb#L49-59)? Thanks!

**Comment by kareemk** [comment]
You may be running an old version of promiscuous on the publisher side

**Comment by kareemk** [comment]
@samsongz did that fix your issue?

**Comment by kareemk** [comment]
Please re-open if this is still an issue.

**Comment by samsongz** [comment]
I'm running 1.0.0.beta3 on both sides so no, that did not solve the issue. I had not set the foreign key correctly on the subscriber side (because I'm mixing databases) but that did not resolve it either. I will try and look closer this weekend. I think it must be a configuration issue on my side because nobody else has this problem. The __promiscuous_missing_record_exception is not being raised when an object is not found in the sync process.

**Comment by kareemk** [comment]
Please share the model files on the publisher and subscriber

**Comment by samsongz** [comment]
Publisher:

``` ruby
class ImportLogItem < ActiveRecord::Base
  include Promiscuous::Publisher

  publish :service, :file_name, :file_downloaded_from, :stats, 
          :created_at, :stats_email_sent_to, :import_state, :log_id,
          :license_type

  attr_accessible :service, :file_name, :file_downloaded_from, 
                  :stats, :stats_email_sent_to, :import_errors, 
                  :import_state, :license_type

... 
end
```

Subscriber:

``` ruby
class ImportLogItem
  include Mongoid::Document
  include Promiscuous::Subscriber

  field :log_id, type: Integer
  field :service, type: String
  field :file_name, type: String
  field :file_downloaded_from, type: String
  field :stats, type: String
  field :stats_email_sent_to, type: String
  field :created_at, type: Date

  subscribe :service, :file_name, :file_downloaded_from, 
            :stats, :stats_email_sent_to, :created_at,
            :foreign_key => :log_id

end
```

Is it possible to set the :foreign_key option using the other Mongoid subscribe block syntax?
