### ISSUE TITLE
Promiscuous or Me?

### ISSUE THREAD

**Issue by AdamKyle** [promiscuous-io/promiscuous#60]
So when I run, on production, `nohup bundle exec promiscuous subscribe` i then check the `nohup.out` for any issues and see:

```
/var/lib/gems/1.9.1/gems/bundler-1.1.5/lib/bundler/runtime.rb:68:in `require': cannot load such file -- pry (LoadError)
        from /var/lib/gems/1.9.1/gems/bundler-1.1.5/lib/bundler/runtime.rb:68:in `block (2 levels) in require'
        from /var/lib/gems/1.9.1/gems/bundler-1.1.5/lib/bundler/runtime.rb:66:in `each'
        from /var/lib/gems/1.9.1/gems/bundler-1.1.5/lib/bundler/runtime.rb:66:in `block in require'
        from /var/lib/gems/1.9.1/gems/bundler-1.1.5/lib/bundler/runtime.rb:55:in `each'
        from /var/lib/gems/1.9.1/gems/bundler-1.1.5/lib/bundler/runtime.rb:55:in `require'
        from /var/lib/gems/1.9.1/gems/bundler-1.1.5/lib/bundler.rb:119:in `require'
        from /home/railsapps/aisiswriter/releases/20140707205243/config/application.rb:12:in `<top (required)>'
        from /home/railsapps/aisiswriter/releases/20140707205243/config/environment.rb:2:in `require'
        from /home/railsapps/aisiswriter/releases/20140707205243/config/environment.rb:2:in `<top (required)>'
        from /home/railsapps/aisiswriter/shared/bundle/ruby/1.9.1/bundler/gems/promiscuous-9bda9a49ac13/lib/promiscuous/cli.rb:207:in `require'
        from /home/railsapps/aisiswriter/shared/bundle/ruby/1.9.1/bundler/gems/promiscuous-9bda9a49ac13/lib/promiscuous/cli.rb:207:in `load_app'
        from /home/railsapps/aisiswriter/shared/bundle/ruby/1.9.1/bundler/gems/promiscuous-9bda9a49ac13/lib/promiscuous/cli.rb:216:in `boot'
        from /home/railsapps/aisiswriter/shared/bundle/ruby/1.9.1/bundler/gems/promiscuous-9bda9a49ac13/gemfiles/bin/promiscuous:5:in `<top (required)>'
        from /home/railsapps/aisiswriter/shared/bundle/ruby/1.9.1/bin/promiscuous:23:in `load'
        from /home/railsapps/aisiswriter/shared/bundle/ruby/1.9.1/bin/promiscuous:23:in `<main>'
```

it states something about pry ..... but near the end it states there is issues with promiscuous??? I have the gems all installed. and on development it works perfectly fine.

**Comment by AdamKyle** [comment]
I found out apparently you require pry ..... interesting. By the way this gem works amazingly in production.
