### ISSUE TITLE
undefined method promiscuous

### ISSUE THREAD

**Issue by AdamKyle** [promiscuous-io/promiscuous#66]
I am getting the following issue:

``` ruby
bundle exec promiscuous publish "Xaaron::User.all"

NoMethodError: undefined method `promiscuous' for #<Xaaron::User:0x007fc68b08b160>                                                                       | 0/1  ETA: ??:??:??
--------------------------------------------------------------------------------
/Users/Adam/Documents/Rails-Projects/AisisPlatform/.bundle/gems/gems/activemodel-4.1.9/lib/active_model/attribute_methods.rb:435:in `method_missing'
/Users/Adam/Documents/Rails-Projects/AisisPlatform/.bundle/gems/gems/activerecord-4.1.9/lib/active_record/attribute_methods.rb:213:in `method_missing'
/Users/Adam/Documents/Rails-Projects/AisisPlatform/.bundle/gems/bundler/gems/promiscuous-d83ad286101b/gemfiles/lib/promiscuous/cli.rb:58:in `block (2 levels) in publish'
/Users/Adam/Documents/Rails-Projects/AisisPlatform/.bundle/gems/gems/activerecord-4.1.9/lib/active_record/relation/delegation.rb:46:in `each'
/Users/Adam/Documents/Rails-Projects/AisisPlatform/.bundle/gems/gems/activerecord-4.1.9/lib/active_record/relation/delegation.rb:46:in `each'
/Users/Adam/Documents/Rails-Projects/AisisPlatform/.bundle/gems/bundler/gems/promiscuous-d83ad286101b/gemfiles/lib/promiscuous/cli.rb:56:in `block in publish'
/Users/Adam/Documents/Rails-Projects/AisisPlatform/.bundle/gems/bundler/gems/promiscuous-d83ad286101b/gemfiles/lib/promiscuous/cli.rb:51:in `each'
/Users/Adam/Documents/Rails-Projects/AisisPlatform/.bundle/gems/bundler/gems/promiscuous-d83ad286101b/gemfiles/lib/promiscuous/cli.rb:51:in `publish'
/Users/Adam/Documents/Rails-Projects/AisisPlatform/.bundle/gems/bundler/gems/promiscuous-d83ad286101b/gemfiles/lib/promiscuous/cli.rb:233:in `run'
/Users/Adam/Documents/Rails-Projects/AisisPlatform/.bundle/gems/bundler/gems/promiscuous-d83ad286101b/gemfiles/lib/promiscuous/cli.rb:217:in `boot'
/Users/Adam/Documents/Rails-Projects/AisisPlatform/.bundle/gems/bundler/gems/promiscuous-d83ad286101b/gemfiles/bin/promiscuous:5:in `<top (required)>'
/Users/Adam/Documents/Rails-Projects/AisisPlatform/.bundle/gems/bin/promiscuous:23:in `load'
/Users/Adam/Documents/Rails-Projects/AisisPlatform/.bundle/gems/bin/promiscuous:23:in `<main>'
```

Do we not publish models this way any more?

**Comment by kareemk** [comment]
Are you sure that you're publishing Xaaron::User. Please share your model file or publisher file.

**Comment by AdamKyle** [comment]
All of these models exist. I have even tried: `publish ':xaaron/users' do ... end` (this doesn't work). 

This was working, is it because of Active Record 4.1.9? I know you don't support this high up in rails, so it might because I'm 50 versions ahead of what you do support. Or it might be something I am doing wrong.

All of these models are from an Engine. 

``` ruby
Promiscuous.define do
  publish Xaaron::User do
    attributes :first_name, :last_name, :email, :user_name, :auth_token, :as => :User
  end

  publish Xaaron::ApiKey do
    attributes :xaaron_users_id, :api_key, :as => :ApiKey
  end

  publish Xaaron::GroupMembership do
    attributes :user_id, :group_id, :role_id, :as => :GroupMembership
  end

  publish Xaaron::Group do
    attributes :group_name, :can_alter, :can_delete, :as => :Group
  end

  publish Xaaron::GroupsRole do
    attributes :group_id, :role_id, :as => :GroupsRole
  end

  publish Xaaron::Permission do
    attributes :permission_name, :can_alter, :can_delete, :as => :Permission
  end

  publish Xaaron::Role do
    attributes :role_name, :can_alter, :can_delete, :as => :Role
  end

  publish Xaaron::RolesPermission do
    attributes :role_id, :permission_id, :as => :RolesPermission
  end

end
```

**Comment by kareemk** [comment]
What version of promiscuous are you using?

**Comment by AdamKyle** [comment]
I have it set to download from: `gem 'promiscuous', :git => 'git@github.com:promiscuous-io/promiscuous.git'`

So: **1.0.0.beta6**

**Comment by kareemk** [comment]
I can't see a reason why this wouldn't work.

How about using http://tmate.io/ to share your terminal with me and i can take a look

**Comment by AdamKyle** [comment]
When your ready you can connect at [tmate] Remote session: ssh siZ5A6GlBmNhTzWZ8wV97gX0f@sf.tmate.io  

Not sure if it will allert me when you connect, as I have never used tmate.  But I get the gist of it.

I also have the command ready to run.

**Comment by kareemk** [comment]
I jumped in and made the necessary changes to your `config/publishers.rb` to get it working. Take a look.

**Comment by AdamKyle** [comment]
I will for sure. I am a bit busy at the moment but I will take a look. Thank you kind sir.
