### ISSUE TITLE
NameError: uninitialized constant ActiveSupport::Autoload when running promiscuous subscribe

### ISSUE THREAD

**Issue by brettallred** [promiscuous-io/promiscuous#77]
I am trying to test out promiscuous but when starting the subscriber I get an NameError: uninitialized constant ActiveSupport::Autoload

I have the latest version of rails (4.2.4) and promiscuous-0.100.5

```
bundle exec promiscuous subscribe
NameError: uninitialized constant ActiveSupport::Autoload

/Users/brett/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/number_helper.rb:3:in `<module:NumberHelper>'
/Users/brett/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/number_helper.rb:2:in `<module:ActiveSupport>'
/Users/brett/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/number_helper.rb:1:in `<top (required)>'
/Users/brett/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/core_ext/numeric/conversions.rb:2:in `require'
/Users/brett/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/core_ext/numeric/conversions.rb:2:in `<top (required)>'
/Users/brett/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/core_ext/numeric.rb:3:in `require'
/Users/brett/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/core_ext/numeric.rb:3:in `<top (required)>'
/Users/brett/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/core_ext.rb:2:in `require'
/Users/brett/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
/Users/brett/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/core_ext.rb:1:in `each'
/Users/brett/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/core_ext.rb:1:in `<top (required)>'
/Users/brett/.rvm/gems/ruby-2.2.1/gems/promiscuous-0.100.5/lib/promiscuous.rb:1:in `require'
/Users/brett/.rvm/gems/ruby-2.2.1/gems/promiscuous-0.100.5/lib/promiscuous.rb:1:in `<top (required)>'
/Users/brett/.rvm/gems/ruby-2.2.1/gems/promiscuous-0.100.5/bin/promiscuous:4:in `require'
/Users/brett/.rvm/gems/ruby-2.2.1/gems/promiscuous-0.100.5/bin/promiscuous:4:in `<top (required)>'
/Users/brett/.rvm/gems/ruby-2.2.1/bin/promiscuous:23:in `load'
/Users/brett/.rvm/gems/ruby-2.2.1/bin/promiscuous:23:in `<main>'
/Users/brett/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/brett/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

When I clone the repo and point my gem path to the local version it works fine.

**Comment by dmbrooking** [comment]
I know this was over a year ago, but do you remember how you resolved this? I'm encountering the same issue.

**Comment by mingxiangchan** [comment]
in case anyone is encountering this error, I resolved it by changing the lines in `/lib/promiscuous.rb` as follows

Source:
` require 'active_support/core_ext'`

Changed to:
```
require 'active_support'
require 'active_support/core_ext'
```
